name: flutter_app_barber
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  pin_view: ^1.0.1

  carousel_slider: ^1.4.1
  carousel_pro: ^1.0.0
  retrofit: ^1.0.1+1
  logger: ^0.8.3
  chopper: ^3.0.1+1
  provider: ^4.0.2
  device_preview: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^3.0.3

  build_runner:
    


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  
  assets:
   - images/
   
  fonts:
    - family: Montserrat-Bold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf 
    - family: Montserrat-Medium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
    - family: Montserrat-Light
      fonts:
        - asset: fonts/Montserrat-Light.ttf           
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
